name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - conda-forge::jupyterlab=3.0.12
  - conda-forge::jupyter=1.0.0
  - conda-forge::seaborn=0.11.1
  - conda-forge::pandas=1.2.3
  - conda-forge::pip=20.3.3
  - conda-forge::pandas-profiling=2.11.0
  - conda-forge::pyarrow=2.0
  - jinja2=3.0.3
  - pip:
      - wandb==0.10.31
      - protobuf==3.20.1