name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.16
  - mlflow=1.14.1
  - ipython=7.21.0
  - notebook=6.2.0
  - jupyter=1.0.0
  - jupyterlab=3.0.12
  - cookiecutter=1.7.2
  - hydra-core=1.0.6
  - matplotlib=3.3.4
  - pandas=1.2.3
  - git=2.30.2
  - pip=20.3.3
  - pip:
      - wandb==0.10.31
      - numpy==1.20.0
      - protobuf==3.20.1

